// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _01_DBQuizGame_Persistence.Entity;

#nullable disable

namespace _01_DBQuizGame_Persistence.Migrations
{
    [DbContext(typeof(DBQuizGameContext))]
    partial class DBQuizGameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.Admin", b =>
                {
                    b.Property<Guid>("IdAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("IdObjectState")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdAdmin");

                    b.HasIndex("IdObjectState");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.Certificate", b =>
                {
                    b.Property<Guid>("IdCertificate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("IdObjectState")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCertificate");

                    b.HasIndex("IdObjectState");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.ObjectState", b =>
                {
                    b.Property<int>("IdObjectState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdObjectState"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdObjectState");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ObjectStates");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.Option", b =>
                {
                    b.Property<Guid>("IdOption")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CorrectSlot")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CorrectSlotGroup")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdObjectState")
                        .HasColumnType("int");

                    b.Property<Guid>("IdQuestion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdOption");

                    b.HasIndex("IdObjectState");

                    b.HasIndex("IdQuestion");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Options");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.Player", b =>
                {
                    b.Property<Guid>("IdPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("IdObjectState")
                        .HasColumnType("int");

                    b.Property<long>("MatricsNo")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("TotalPoints")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPlayer");

                    b.HasIndex("IdObjectState");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.PlayerCertificate", b =>
                {
                    b.Property<Guid>("IdPlayerCertificate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdCertificate")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdObjectState")
                        .HasColumnType("int");

                    b.Property<Guid>("IdPlayer")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PointsAcquired")
                        .HasColumnType("int");

                    b.Property<int>("TimeTaken")
                        .HasColumnType("int");

                    b.Property<int>("TotalAttempt")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPlayerCertificate");

                    b.HasIndex("IdCertificate");

                    b.HasIndex("IdObjectState");

                    b.HasIndex("IdPlayer");

                    b.ToTable("PlayerCertificates");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.PlayerQuiz", b =>
                {
                    b.Property<Guid>("IdPlayerQuiz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdObjectState")
                        .HasColumnType("int");

                    b.Property<Guid>("IdPlayer")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdQuiz")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PointsAcquired")
                        .HasColumnType("int");

                    b.Property<int>("TimeTaken")
                        .HasColumnType("int");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPlayerQuiz");

                    b.HasIndex("IdObjectState");

                    b.HasIndex("IdPlayer");

                    b.HasIndex("IdQuiz");

                    b.ToTable("PlayerQuizzes");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.Question", b =>
                {
                    b.Property<Guid>("IdQuestion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdObjectState")
                        .HasColumnType("int");

                    b.Property<int>("IdQuestionType")
                        .HasColumnType("int");

                    b.Property<Guid>("IdQuiz")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdQuestion");

                    b.HasIndex("IdObjectState");

                    b.HasIndex("IdQuestionType");

                    b.HasIndex("IdQuiz");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.QuestionType", b =>
                {
                    b.Property<int>("IdQuestionType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuestionType"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("IdObjectState")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalOption")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdQuestionType");

                    b.HasIndex("IdObjectState");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("QuestionTypes");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.Quiz", b =>
                {
                    b.Property<Guid>("IdQuiz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ExpectedCompletionTime")
                        .HasColumnType("int");

                    b.Property<int>("IdObjectState")
                        .HasColumnType("int");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalQuestion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdQuiz");

                    b.HasIndex("IdObjectState");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.QuizCertificate", b =>
                {
                    b.Property<Guid>("IdQuizCertificate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdCertificate")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdObjectState")
                        .HasColumnType("int");

                    b.Property<Guid>("IdQuiz")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdQuizCertificate");

                    b.HasIndex("IdCertificate");

                    b.HasIndex("IdObjectState");

                    b.HasIndex("IdQuiz");

                    b.ToTable("QuizCertificates");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.Admin", b =>
                {
                    b.HasOne("_01_DBQuizGame_Persistence.Entity.ObjectState", "ObjectState1")
                        .WithMany("Admins1")
                        .HasForeignKey("IdObjectState")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ObjectState1");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.Certificate", b =>
                {
                    b.HasOne("_01_DBQuizGame_Persistence.Entity.ObjectState", "ObjectState1")
                        .WithMany("Certificates1")
                        .HasForeignKey("IdObjectState")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ObjectState1");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.Option", b =>
                {
                    b.HasOne("_01_DBQuizGame_Persistence.Entity.ObjectState", "ObjectState1")
                        .WithMany("Options1")
                        .HasForeignKey("IdObjectState")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_01_DBQuizGame_Persistence.Entity.Question", "Question1")
                        .WithMany("Options1")
                        .HasForeignKey("IdQuestion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ObjectState1");

                    b.Navigation("Question1");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.Player", b =>
                {
                    b.HasOne("_01_DBQuizGame_Persistence.Entity.ObjectState", "ObjectState1")
                        .WithMany("Players1")
                        .HasForeignKey("IdObjectState")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ObjectState1");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.PlayerCertificate", b =>
                {
                    b.HasOne("_01_DBQuizGame_Persistence.Entity.Certificate", "Certificate1")
                        .WithMany("PlayerCertificates1")
                        .HasForeignKey("IdCertificate")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_01_DBQuizGame_Persistence.Entity.ObjectState", "ObjectState1")
                        .WithMany("PlayerCertificates1")
                        .HasForeignKey("IdObjectState")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_01_DBQuizGame_Persistence.Entity.Player", "Player1")
                        .WithMany("PlayerCertificates1")
                        .HasForeignKey("IdPlayer")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Certificate1");

                    b.Navigation("ObjectState1");

                    b.Navigation("Player1");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.PlayerQuiz", b =>
                {
                    b.HasOne("_01_DBQuizGame_Persistence.Entity.ObjectState", "ObjectState1")
                        .WithMany("PlayerQuizzes1")
                        .HasForeignKey("IdObjectState")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_01_DBQuizGame_Persistence.Entity.Player", "Player1")
                        .WithMany("PlayerQuizzes1")
                        .HasForeignKey("IdPlayer")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_01_DBQuizGame_Persistence.Entity.Quiz", "Quiz1")
                        .WithMany("PlayerQuizzes1")
                        .HasForeignKey("IdQuiz")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ObjectState1");

                    b.Navigation("Player1");

                    b.Navigation("Quiz1");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.Question", b =>
                {
                    b.HasOne("_01_DBQuizGame_Persistence.Entity.ObjectState", "ObjectState1")
                        .WithMany("Questions1")
                        .HasForeignKey("IdObjectState")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_01_DBQuizGame_Persistence.Entity.QuestionType", "QuestionType1")
                        .WithMany("Questions1")
                        .HasForeignKey("IdQuestionType")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_01_DBQuizGame_Persistence.Entity.Quiz", "Quiz1")
                        .WithMany("Questions1")
                        .HasForeignKey("IdQuiz")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ObjectState1");

                    b.Navigation("QuestionType1");

                    b.Navigation("Quiz1");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.QuestionType", b =>
                {
                    b.HasOne("_01_DBQuizGame_Persistence.Entity.ObjectState", "ObjectState1")
                        .WithMany("QuestionTypes1")
                        .HasForeignKey("IdObjectState")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ObjectState1");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.Quiz", b =>
                {
                    b.HasOne("_01_DBQuizGame_Persistence.Entity.ObjectState", "ObjectState1")
                        .WithMany("Quizzes1")
                        .HasForeignKey("IdObjectState")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ObjectState1");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.QuizCertificate", b =>
                {
                    b.HasOne("_01_DBQuizGame_Persistence.Entity.Certificate", "Certificate1")
                        .WithMany("QuizCertificates1")
                        .HasForeignKey("IdCertificate")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_01_DBQuizGame_Persistence.Entity.ObjectState", "ObjectState1")
                        .WithMany("QuizCertificates1")
                        .HasForeignKey("IdObjectState")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_01_DBQuizGame_Persistence.Entity.Quiz", "Quiz1")
                        .WithMany("QuizCertificates1")
                        .HasForeignKey("IdQuiz")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Certificate1");

                    b.Navigation("ObjectState1");

                    b.Navigation("Quiz1");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.Certificate", b =>
                {
                    b.Navigation("PlayerCertificates1");

                    b.Navigation("QuizCertificates1");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.ObjectState", b =>
                {
                    b.Navigation("Admins1");

                    b.Navigation("Certificates1");

                    b.Navigation("Options1");

                    b.Navigation("PlayerCertificates1");

                    b.Navigation("PlayerQuizzes1");

                    b.Navigation("Players1");

                    b.Navigation("QuestionTypes1");

                    b.Navigation("Questions1");

                    b.Navigation("QuizCertificates1");

                    b.Navigation("Quizzes1");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.Player", b =>
                {
                    b.Navigation("PlayerCertificates1");

                    b.Navigation("PlayerQuizzes1");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.Question", b =>
                {
                    b.Navigation("Options1");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.QuestionType", b =>
                {
                    b.Navigation("Questions1");
                });

            modelBuilder.Entity("_01_DBQuizGame_Persistence.Entity.Quiz", b =>
                {
                    b.Navigation("PlayerQuizzes1");

                    b.Navigation("Questions1");

                    b.Navigation("QuizCertificates1");
                });
#pragma warning restore 612, 618
        }
    }
}
